# https://taskfile.dev

version: '3'

vars:
  WORKSPACES:
    - aws
    - changelog
    - confluence
    - rag-ai
    - time-saver
  YARN_VERSION: 4.9.1

tasks:
  default:
    dir: ./
    cmds:
      - yarn install
    silent: true

  bump:yarn:
    cmds:
      - |
        YARN_VERSION="{{.YARN_VERSION}}"
        WORKING_DIRECTORY="$(pwd)"
        yarn set version "${YARN_VERSION}"
        yarn install
        yarn dedupe
        {{range $index, $workspace := .WORKSPACES}}
        echo "Updating yarn in \"{{$workspace}}\""
        cd "${WORKING_DIRECTORY}/workspaces/{{$workspace}}/"
        yarn set version "${YARN_VERSION}"
        yarn install
        yarn dedupe
        {{end}}

  bump:framework:
    cmds:
      - |
        WORKING_DIRECTORY="$(pwd)"
        {{range $index, $workspace := .WORKSPACES}}
        echo "Processing \"{{$workspace}}\""
        cd "${WORKING_DIRECTORY}/workspaces/{{$workspace}}/"
        yarn install
        yarn backstage-cli versions:bump
        yarn tsc
        yarn build:api-reports:only
        yarn fix
        yarn prettier --write .
        yarn lint
        yarn dedupe
        {{end}}
