name: PR
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  issue_comment:
    types:
      - created

jobs:
  sync:
    runs-on: ubuntu-latest

    # Avoid running on issue comments
    if: github.repository == 'alithya-oss/backstage-plugins' && ( github.event.pull_request || github.event.issue.pull_request )
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - name: PR sync
        uses: backstage/actions/pr-sync@a9e1b58ad52aaf319264e18c3ff6887a4c824b52 # v0.7.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN  }}
          app-id: ${{ secrets.BACKSTAGE_GOALIE_APPLICATION_ID }}
          private-key: ${{ secrets.BACKSTAGE_GOALIE_PRIVATE_KEY }}
          installation-id: ${{ secrets.BACKSTAGE_GOALIE_INSTALLATION_ID }}
          auto-assign: false
